### ISSUE TITLE
Red rings in certain situations inside earths atmosphere

### ISSUE THREAD

**Issue by itsaps** [cosmoscout/cosmoscout-vr#372] opened 2024-04-18 19:56 UTC
## Describe the Bug
Hi, thank you for the great software! I am taking first steps with CosmoScout VR and thought this might be interesting (this is my first bug report ever): 
In certain situations there appear red rings on the surface of the earth (see screenshot). The situation is viewing the unlit side of earth, about 1km high pointing towards the surface. This artefact is gone if the camera is moved higher or lower than 1km. Also if the clouds  are disabled or the cloud height is changed, this issue is gone. So it seems to be caused by the cloud renderer?

I am using the precompiled binaries provided from the 1.9.0 release.

![image](https://github.com/cosmoscout/cosmoscout-vr/assets/45340500/2cc9b430-03aa-45fe-b3cf-6af97347dc39)

1. Go to earth
2. Set time and location similar to screenshot

or
1. Go to earth
2. move to dark side of earth
3.  zoom to altitude around 1000m

## Expected Behavior
The red artefacts are not expected

## System
 - CosmoScout VR v1.9.0
 - OS: Win 10
 - Compiler: binaries (cosmoscout-vr-win64.zip)
 - Graphics Card AMD Radeon RX 7800 XT

**Comment by JonasGilg** [comment] 2024-04-19 07:47
Thank you very much for this report. We will have a look at it.

**Comment by JonasGilg** [comment] 2024-04-19 07:52
@Schneegans, since you are the author of the atmospheres plugin, I think it is best, if you give this a look.

**Comment by Schneegans** [comment] 2024-04-24 08:22
This looks... interesting :smile: 

I'll have a look as soon as I am back in the office!

**Comment by Schneegans** [comment] 2024-05-08 18:00
Thanks again for the report! I was indeed able to reproduce the issue. I think that it should be fixed now in the current `main` branch.

**Closed** 2024-05-08 18:00 UTC
Labels: bug, csp-atmospheres
